#!/bin/bash

CWD=$(pwd)

FILES=(LICENSE README.md screenshot.png)

for FILE in "${FILES[@]}"; do
    if ! cmp -s "${FILE}" "./UnityPackage/${FILE}"; then
        echo "${FILE} needs to be synced to the UnityPackage folder!"
        exit 1
    fi
done

cd RhythmGameUtilities

find . -type f -name "*.cs" -not -path '*/obj/*' -not -path '*/bin/*' -print0 |
    while IFS= read -r -d '' FILE; do
        if ! cmp -s "${FILE}" "../UnityPackage/${FILE}"; then
            echo "${FILE} needs to be synced to the UnityPackage folder!"
            exit 1
        fi
    done

cd "${CWD}"

cd RhythmGameUtilities.Tests

find . -type f -name "*.cs" -not -path '*/obj/*' -not -path '*/bin/*' -print0 |
    while IFS= read -r -d '' FILE; do
        if ! cmp -s "${FILE}" "../UnityPackage/Editor/Tests/${FILE}"; then
            echo "${FILE} needs to be synced to the UnityPackage/Editor/Tests folder!"
            exit 1
        fi
    done

cd "${CWD}"
