#!/bin/bash

CWD=$(pwd)

FOLDERS=("RhythmGameUtilities/Libs/" "UnityPackage/Libs/")

for FOLDER in "${FOLDERS[@]}"; do
    if [[ $(
        git diff HEAD --exit-code --quiet --binary "${FOLDER}"
        echo $?
    ) -ne 0 ]]; then
        echo "Do not commit build files."
        exit 1
    fi
done

FILES=(LICENSE README.md screenshot.png)

for FILE in "${FILES[@]}"; do
    if ! cmp -s "${FILE}" "./UnityPackage/${FILE}"; then
        echo "${FILE} needs to be synced to the UnityPackage folder!"
        exit 1
    fi
done

cd RhythmGameUtilities

find . -type f -name "*.cs" -not -path '*/obj/*' -not -path '*/bin/*' -print0 |
    while IFS= read -r -d '' FILE; do
        if ! cmp -s "${FILE}" "../UnityPackage/${FILE}"; then
            echo "${FILE} needs to be synced to the UnityPackage folder!"
            exit 1
        fi
    done

cd "${CWD}"

cd RhythmGameUtilities.Tests

find . -type f -name "*.cs" -not -path '*/obj/*' -not -path '*/bin/*' -print0 |
    while IFS= read -r -d '' FILE; do
        if ! cmp -s "${FILE}" "../UnityPackage/Editor/Tests/${FILE}"; then
            echo "${FILE} needs to be synced to the UnityPackage/Editor/Tests folder!"
            exit 1
        fi
    done

cd "${CWD}"
